### ISSUE TITLE
1.5 branch tests do not work with jackson 2.10.3/2.10.4

### ISSUE THREAD

**Issue by pjfanning** [swagger-akka-http/swagger-akka-http#171]
swagger-core 1.5/1.6 does not yet support jackson 2.11.

The swagger-akka-http 1.5 branch tests work with jackaon 2.10.2 but fail with newer versions.

[ERROR] [06/13/2020 13:50:44.390] [pool-7-thread-5-ScalaTest-running-SwaggerHttpServiceSpec] [akka.actor.ActorSystemImpl(com-github-swagger-akka-SwaggerHttpServiceSpec)] Error during processing of request: 'Direct self-reference leading to cycle (through reference chain: io.swagger.models.Swagger["definitions"]->scala.collection.convert.Wrappers$MutableMapWrapper["ListReply"]->io.swagger.models.ModelImpl["properties"]->java.util.LinkedHashMap["items"]->io.swagger.models.properties.ArrayProperty["readOnly"])'. Completing with 500 Internal Server Error response. To change default exception handling behavior, provide a custom ExceptionHandler.
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Direct self-reference leading to cycle (through reference chain: io.swagger.models.Swagger["definitions"]->scala.collection.convert.Wrappers$MutableMapWrapper["ListReply"]->io.swagger.models.ModelImpl["properties"]->java.util.LinkedHashMap["items"]->io.swagger.models.properties.ArrayProperty["readOnly"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1191)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter._handleSelfReference(BeanPropertyWriter.java:944)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:721)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166)

**Comment by pjfanning** [comment]
will probably wait for https://github.com/swagger-api/swagger-core/pull/3574 and next swagger 1.6.x release

**Comment by pjfanning** [comment]
fixed in v1.1.2
