### ISSUE TITLE
Fail to return case class with trait

### ISSUE THREAD

**Issue by favetelinguis** [swagger-akka-http/swagger-akka-http#36]
Not sure why im getting this error. I cant find any example where a case class extends a sealed trait. Might this be the cause of the error?

```
@Api(value = "/", produces = "application/json")
@Path("/session")
class AuthenticationRoute(handler: AuthenticationHandler) extends PartialRoute with FailFastCirceSupport {

  override val route: Route = authenticationStatus ~ authenticationStatus2

  @Path("/authStatus")
  @ApiOperation(value = "Return session status", notes = "", nickname = "anonymousHello", httpMethod = "GET")
  @ApiResponses(Array(
    new ApiResponse(code = 200, message = "Return Hello Greeting", response = classOf[SessionCreated]),
    new ApiResponse(code = 500, message = "Internal server error")
  ))
  def authenticationStatus =
    path("session" / "authStatus") {
      get {
        complete(handler.authenticationStatus.mapTo[SessionCreated])
      }
    }
}
```

```
  sealed trait SessionEvent
  object SessionEvent {
    @ApiModel(description = "The session token")
    case class SessionCreated(
                               @(ApiModelProperty @field)("Token!")
                               val sessionToken: String
                             ) extends SessionEvent
  }
```

```
11:31:22 [default-akka.actor.default-dispatcher-19] DEBUG io.swagger.jaxrs.Reader - picking up response class from method public scala.Function1 com.bfg.infrastructure.server.routes.AuthenticationRoute.authenticationStatus()
11:31:22 [default-akka.actor.default-dispatcher-19] DEBUG io.swagger.converter.ModelConverters - adding ModelConverter: io.swagger.scala.converter.SwaggerScalaModelConverter@451baad9
11:31:22 [default-akka.actor.default-dispatcher-19] DEBUG i.s.c.ModelConverterContextImpl - resolveProperty scala.Function1<akka.http.scaladsl.server.RequestContext, scala.concurrent.Future<akka.http.scaladsl.server.RouteResult>>
11:31:22 [default-akka.actor.default-dispatcher-19] DEBUG io.swagger.jackson.ModelResolver - resolveProperty [simple type, class scala.Function1<akka.http.scaladsl.server.RequestContext,scala.concurrent.Future<akka.http.scaladsl.server.RouteResult>>]
11:31:22 [default-akka.actor.default-dispatcher-19] DEBUG i.s.c.ModelConverterContextImpl - resolve [simple type, class scala.Function1<akka.http.scaladsl.server.RequestContext,scala.concurrent.Future<akka.http.scaladsl.server.RouteResult>>]
11:31:22 [default-akka.actor.default-dispatcher-19] DEBUG i.s.c.ModelConverterContextImpl - trying extension io.swagger.scala.converter.SwaggerScalaModelConverter@451baad9
11:31:22 [default-akka.actor.default-dispatcher-19] DEBUG io.swagger.jackson.ModelResolver - Can't check class [simple type, class scala.Function1<akka.http.scaladsl.server.RequestContext,scala.concurrent.Future<akka.http.scaladsl.server.RouteResult>>], scala.Function1
11:31:22 [default-akka.actor.default-dispatcher-19] DEBUG i.s.c.ModelConverterContextImpl - resolve interface scala.Function1
11:31:22 [default-akka.actor.default-dispatcher-19] DEBUG i.s.c.ModelConverterContextImpl - trying extension io.swagger.scala.converter.SwaggerScalaModelConverter@451baad9
11:31:23 [default-akka.actor.default-dispatcher-19] DEBUG i.s.c.ModelConverterContextImpl - defineModel Function1 io.swagger.models.ModelImpl@5925ab17
11:31:23 [default-akka.actor.default-dispatcher-19] DEBUG i.s.c.ModelConverterContextImpl - defineModel Function1 io.swagger.models.ModelImpl@5925ab17
11:31:23 [default-akka.actor.default-dispatcher-19] DEBUG i.s.c.ModelConverterContextImpl - defineModel Function1RequestContextFutureRouteResult io.swagger.models.ModelImpl@7ae6d168
11:31:23 [default-akka.actor.default-dispatcher-19] DEBUG i.s.c.ModelConverterContextImpl - defineModel Function1RequestContextFutureRouteResult io.swagger.models.ModelImpl@7ae6d168
11:31:23 [default-akka.actor.default-dispatcher-19] DEBUG io.swagger.converter.ModelConverters - ModelConverters readAll from scala.Function1<akka.http.scaladsl.server.RequestContext, scala.concurrent.Future<akka.http.scaladsl.server.RouteResult>>
11:31:23 [default-akka.actor.default-dispatcher-19] DEBUG i.s.c.ModelConverterContextImpl - resolve scala.Function1<akka.http.scaladsl.server.RequestContext, scala.concurrent.Future<akka.http.scaladsl.server.RouteResult>>
11:31:23 [default-akka.actor.default-dispatcher-19] DEBUG i.s.c.ModelConverterContextImpl - trying extension io.swagger.scala.converter.SwaggerScalaModelConverter@451baad9
11:31:23 [default-akka.actor.default-dispatcher-19] DEBUG i.s.c.ModelConverterContextImpl - resolve interface scala.Function1
11:31:23 [default-akka.actor.default-dispatcher-19] DEBUG i.s.c.ModelConverterContextImpl - trying extension io.swagger.scala.converter.SwaggerScalaModelConverter@451baad9
11:31:23 [default-akka.actor.default-dispatcher-19] DEBUG i.s.c.ModelConverterContextImpl - defineModel Function1 io.swagger.models.ModelImpl@5925ab17
11:31:23 [default-akka.actor.default-dispatcher-19] DEBUG i.s.c.ModelConverterContextImpl - defineModel Function1 io.swagger.models.ModelImpl@5925ab17
11:31:23 [default-akka.actor.default-dispatcher-19] DEBUG i.s.c.ModelConverterContextImpl - defineModel Function1RequestContextFutureRouteResult io.swagger.models.ModelImpl@7ae6d168
11:31:23 [default-akka.actor.default-dispatcher-19] DEBUG i.s.c.ModelConverterContextImpl - defineModel Function1RequestContextFutureRouteResult io.swagger.models.ModelImpl@7ae6d168
11:31:23 [default-akka.actor.default-dispatcher-19] DEBUG i.s.c.ModelConverterContextImpl - resolveProperty class com.bfg.domain.model.DomainEvents$SessionEvent$SessionCreated
11:31:23 [default-akka.actor.default-dispatcher-19] DEBUG io.swagger.jackson.ModelResolver - resolveProperty [simple type, class com.bfg.domain.model.DomainEvents$SessionEvent$SessionCreated]
Uncaught error from thread [default-akka.actor.default-dispatcher-19] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[default]
java.lang.InternalError: Malformed class name
	at java.lang.Class.getSimpleName(Class.java:1330)
	at java.lang.Class.getCanonicalName(Class.java:1399)
	at io.swagger.jackson.ModelResolver._isOptionalType(ModelResolver.java:173)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:155)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:110)
	at io.swagger.scala.converter.SwaggerScalaModelConverter.resolveProperty(SwaggerScalaModelConverter.scala:55)
	at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:80)
	at io.swagger.converter.ModelConverters.readAsProperty(ModelConverters.java:58)
	at io.swagger.jaxrs.Reader.addResponse(Reader.java:1017)
	at io.swagger.jaxrs.Reader.parseMethod(Reader.java:939)
	at io.swagger.jaxrs.Reader.read(Reader.java:322)
	at io.swagger.jaxrs.Reader.read(Reader.java:172)
	at com.github.swagger.akka.SwaggerHttpService.generateSwaggerJson(SwaggerHttpService.scala:93)
	at com.github.swagger.akka.SwaggerHttpService.generateSwaggerJson$(SwaggerHttpService.scala:91)
	at com.bfg.infrastructure.server.routes.SwaggerRoute$$anon$1.generateSwaggerJson(SwaggerRoute.scala:21)
	at com.github.swagger.akka.SwaggerHttpService.$anonfun$routes$3(SwaggerHttpService.scala:120)
	at akka.http.scaladsl.server.directives.RouteDirectives.$anonfun$complete$1(RouteDirectives.scala:47)
	at akka.http.scaladsl.server.StandardRoute$$anon$1.apply(StandardRoute.scala:19)
	at akka.http.scaladsl.server.StandardRoute$$anon$1.apply(StandardRoute.scala:19)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:61)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:154)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRequestContext$2(BasicDirectives.scala:43)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:154)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$2(RouteConcatenation.scala:47)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
	at akka.http.scaladsl.util.FastFuture$.flatMap$extension(FastFuture.scala:26)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:154)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResultWith$2(BasicDirectives.scala:67)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:154)
	at akka.http.scaladsl.server.directives.ExecutionDirectives.$anonfun$handleExceptions$2(ExecutionDirectives.scala:32)
	at akka.http.scaladsl.server.Route$.$anonfun$asyncHandler$1(Route.scala:81)
	at akka.stream.impl.fusing.MapAsync$$anon$23.onPush(Ops.scala:1172)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:499)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:462)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:368)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:457)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:725)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:740)
	at akka.actor.Actor.aroundReceive(Actor.scala:513)
	at akka.actor.Actor.aroundReceive$(Actor.scala:511)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:650)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:519)
	at akka.actor.ActorCell.invoke(ActorCell.scala:488)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[ERROR] [SECURITY][05/25/2017 11:31:23.243] [default-akka.actor.default-dispatcher-19] [akka.actor.ActorSystemImpl(default)] Uncaught error from thread [default-akka.actor.default-dispatcher-19] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
[INFO] [05/25/2017 11:31:23.248] [Thread-0] [CoordinatedShutdown(akka://default)] Starting coordinated shutdown from JVM shutdown hook
11:31:23 [default-akka.actor.default-dispatcher-2] INFO  com.bfg.infrastructure.server.Server - Shutting down
[ERROR] [05/25/2017 11:31:23.265] [default-akka.actor.default-dispatcher-2] [akka.actor.ActorSystemImpl(default)] Outgoing request stream error (akka.stream.AbruptTerminationException)

Process finished with exit code 255
```

**Comment by pjfanning** [comment]
swagger-akka-http is just a wrapper around the core swagger.io code - I forked swagger-scala-module and added a test based on your case class and it works ok (one oddity is that the token property is not required=true)

One thing you could check is that all the swagger jars on your classpath are the latest available.

**Comment by favetelinguis** [comment]
Hmm ok must be something else then, thanks for verifying it works on your end.

**Comment by pjfanning** [comment]
https://github.com/pjfanning/swagger-scala-module/commit/088fb3ed9fcaa9b80073b4cc1b9b2e7e1f80b42f
